name: buildx-on-pr

on:
  pull_request:
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64 #,linux/arm64
  REGISTRY: ghcr.io

jobs:
  buildx-on-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Set up variable repository name
        run: echo "IMAGE_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Image registry login
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildx and Push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          context: .
          file: Containerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:testing
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:testing-${{ github.event.pull_request.number }}
          platforms: ${{ env.PLATFORMS }}
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
