name: buildx

on:
  workflow_dispatch:
  # pull_request:
  push:
    branches:
      - 'master'

env:
  IMAGE_NAME: ghcr.io/truestory1/alpine-netops
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  buildx:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initial Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          tags: ${{ env.IMAGE_NAME }}:testing
          platforms: ${{ env.PLATFORMS }}
          provenance: false

      - name: Load Built Image and Get Variables
        id: vars
        run: |
          docker buildx build \
            -f Containerfile \
            -t ${{ env.IMAGE_NAME }}:testing \
            --platform=linux/amd64 \
            --load \
            .
          docker run -d ${{ env.IMAGE_NAME }}:testing
          CID=$(docker run -d ${{ env.IMAGE_NAME }}:testing sleep 9999)
          echo "CID=$CID"
          VER_FULL=$(docker exec $CID date +"%Y.%m.%d")
          echo "VER_FULL=$VER_FULL"
          docker rm -f $CID
          echo "VER_FULL=$VER_FULL" >> $GITHUB_ENV
          VER_MAJOR=$(echo $VER_FULL | cut -d. -f-1)
          VER_MINOR=$(echo $VER_FULL | cut -d. -f-2)
          echo "VER_MAJOR=$VER_MAJOR" >> $GITHUB_ENV
          echo "VER_MINOR=$VER_MINOR" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildx and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VER_FULL }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VER_MINOR }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VER_MAJOR }}
          platforms: ${{ env.PLATFORMS }}
          provenance: false
          push: true
